[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    moononournation/GFX Library for Arduino@^1.5.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    ewpa/LibSSH-ESP32
    bblanchon/ArduinoJson @ ^7.4.2
  
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

board_build.partitions =  huge_app.csv

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
  +<clumsyPL/>
